refactor: GitHub Actions 파일 작성

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -10,11 +10,11 @@ permissions:
   contents: read
 
 jobs:
-  build-and-deploy:
+  build-docker-image:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout
         uses: actions/checkout@v3
 
       - name: Set up JDK 17
@@ -35,19 +35,11 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Build Docker image
+      - name: Docker Image Build
         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} -f infra/Dockerfile .
 
-      - name: Push Docker image
+      - name: DockerHub Push
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
-
-      - name: Create directory on EC2
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_KEY }}
-          script: mkdir -p /home/ec2-user/myproject
 
       - name: Copy docker-compose.yml to EC2
         uses: appleboy/scp-action@v0.1.1
@@ -58,20 +50,6 @@ jobs:
           source: "infra/docker-compose.yml"
           target: "/home/ec2-user/myproject/docker-compose.yml"
 
-      - name: Verify docker-compose.yml on EC2
-        uses: appleboy/ssh-action@v0.1.6
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.EC2_KEY }}
-          script: |
-            cd /home/ec2-user/myproject
-            if [ ! -f docker-compose.yml ]; then
-              echo "docker-compose.yml not found!"
-              exit 1
-            fi
-            echo "docker-compose.yml is present."
-
       - name: Deploy to EC2
         uses: appleboy/ssh-action@v0.1.6
         with:
@@ -80,6 +58,11 @@ jobs:
           key: ${{ secrets.EC2_KEY }}
           script: |
             cd /home/ec2-user/myproject
+            
+            if [ ! -f docker-compose.yml ]; then
+              echo "docker-compose.yml not found!"
+              exit 1
+            fi
 
             echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee .env
             echo "DB_NAME=${{ secrets.DB_NAME }}" | sudo tee -a .env
