refactor: GitHub Actions 파일 수정

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -50,6 +50,15 @@ jobs:
           source: "infra/docker-compose.yml"
           target: "/home/ec2-user/myproject/docker-compose.yml"
 
+      - name: Copy .env to EC2
+        uses: appleboy/scp-action@v0.1.1
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_KEY }}
+          source: "infra/.env"
+          target: "/home/ec2-user/myproject/.env"
+
       - name: Deploy to EC2
         uses: appleboy/ssh-action@v0.1.6
         with:
@@ -64,16 +73,11 @@ jobs:
               exit 1
             fi
 
-            # Create .env file
-            sudo tee .env <<EOF
-  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
-  DB_NAME=${{ secrets.DB_NAME }}
-  DB_USERNAME=${{ secrets.DB_USERNAME }}
-  DB_URL=${{ secrets.DB_URL }}
-  DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
-  PROJECT_NAME=${{ secrets.PROJECT_NAME }}
-  EOF
-  
-  sudo /usr/local/bin/docker-compose down
-  sudo /usr/local/bin/docker-compose pull
-  sudo /usr/local/bin/docker-compose up -d
+            if [ ! -f .env ]; then
+              echo ".env file not found!"
+              exit 1
+            fi
+
+            sudo /usr/local/bin/docker-compose down
+            sudo /usr/local/bin/docker-compose pull
+            sudo /usr/local/bin/docker-compose up -d
