refactor: 경로 수정

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -36,7 +36,7 @@ jobs:
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
       - name: Docker Image Build
-        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} .
+        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} -f infra/Dockerfile .
 
       - name: DockerHub Push
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
@@ -49,6 +49,11 @@ jobs:
           key: ${{ secrets.EC2_KEY }}
           script: |
             cd /home/ec2-user/infra
+            
+            if [ ! -f docker-compose.yml ]; then
+              echo "docker-compose.yml not found!"
+              exit 1
+            fi
 
             echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee .env
             echo "DB_NAME=${{ secrets.DB_NAME }}" | sudo tee -a .env
